[package]
name = "lern"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { git = "https://github.com/iced-rs/iced.git", features = ["tokio"]}
iced_aw = { git = "https://github.com/iced-rs/iced_aw.git", rev = "4dfb6a27004ecf309b73c440b8cde78355c49448", default-features = false, features = ["tabs"] }
regex = "1.10.5"
rusqlite = { version = "0.31.0", features = ["bundled"] }
serde = "1.0.203"
serde_json = "1.0.117"
tokio = { version = "1.38.0", features = ["full"] }
tokio-rusqlite = "0.5.1"
